apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-status-app.fullname" . }}
  labels:
    {{- include "cluster-status-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-status-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-status-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/myapp
              readOnly: true
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cluster-status-app.fullname" . }}-config
        {{- toYaml .Values.volumes | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}